baseURL = "https://lkslee.github.io/Meteo/" 
languageCode = "zh-cn" 
title = "Meteo" 
theme = "PaperMod" 

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3